version: '3.8'

services:
    
    postgres:        
        image: postgres:14.5
        ports:
        - 5432:5432
      
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: UNlocky@1
            POSTGRES_DB: covidvaccinationdb

       
      
    covidvaccination:        
        build: .    #Docker file is in current directory
        #image: imagename:tag
        ports:
        - 8085:8085 #mapping host port with container port
     
  
